spring.profiles.include: database, consul

spring:
  application:
    name: muses-recommend

server:
  port: 9070
  servlet:
    context-path: /
    session:
      timeout: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
        exclude: info
    health:
      consul.enabled: false
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true #在内存中保存统计监控数据
---
spring:
  profile: consul
  cloud:
    consul:
      host: 127.0.0.1    # Consul 服务器地址
      port: 8499         # Consul 服务器端口
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${random.value}
        register: true   # 将服务注册到 Consul
        prefer-ip-address: true
        heartbeat:
          enabled: true
          reregister-service-on-failure: true #consul重启后重新注册
        enabled: true
        deregister: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-timeout: 30s
        health-check-path: /actuator/health
        automatic-registry-reconnection: true
---
spring:
  profile: database
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      max-idle: 8
      min-idle: 8
      jdbc-url: jdbc:mysql://182.168.131.24:3306/muses_biz?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: "1234"
    clickhouse:
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      jdbc-url: jdbc:clickhouse://182.168.131.24:8123/muses_warehouse
      password: 4321
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    mysql:
      database: MYSQL
      hibernate:
        ddl-auto: validate
        naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
      properties:
        hibernate:
          javax.persistence.query.timeout: 3
      show-sql: true
    clickhouse:
      hibernate:
        ddl-auto: update
      show-sql: true
